# Scan this file for changes every 10 seconds
refresh_rate: 10 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      pattern: "{l} {d(%Y/%m/%d %H:%M:%S)} {f}:{L}: {m}{n}"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: info
  appenders:
    - stdout
